spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:rest
    driverClassName: org.h2.Driver
    name:
    username: sa
    password: sa

server:
  port: 8080
  compression:
    enabled: true
